"""add image column to user table and trip table

Revision ID: 6d217d6a55fc
Revises: fae1449da11e
Create Date: 2023-09-29 12:27:45.409195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d217d6a55fc'
down_revision = 'fae1449da11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_image_url', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('trip_image_url')

    # ### end Alembic commands ###
