"""remove trip_user table object

Revision ID: 7537daf9b076
Revises: 47a9bd273611
Create Date: 2023-10-03 11:23:55.808330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7537daf9b076'
down_revision = '47a9bd273611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips_users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips_users',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('trip_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='fk_trips_users_trip_id_trips'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_trips_users_user_id_users')
    )
    # ### end Alembic commands ###
